---
name: Lint code

on:
  push:
    branches-ignore: [test]
  pull_request:
    branches-ignore: [test]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install codespell
        run: pip install codespell tomli

      - name: Run codespell
        run: codespell

